name: Hello GitHub Actions

on:
  push:
    branches: [ master ]

jobs:
  say-hello-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Python script
        run: python hello.py
        shell: cmd
 
